name: use_case
description: Architecture agnostic approach to UseCase implementation.
version: 1.0.0
homepage: https://github.com/camrongiuliani/use_case

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  synchronized: ^3.0.0+3
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  freezed: ^2.1.0+1

flutter:
